### ISSUE TITLE
Change the relationship statement

### ISSUE THREAD

**Issue by leliel12** [toros-astro/corral#1]
for every statatemet like

```python
stackstate = db.relationship(
    "StackState", backref=db.backref('stack_statechanges', order_by=id))
```

make look like

```python
stackstate_id = Column(Integer, ForeignKey('stackstate.id'))
stackstate = db.relationship(
        "StackState", backref=db.backref('stack_statechanges', order_by=id))
```
**Docs:**
http://docs.sqlalchemy.org/en/rel_1_1/orm/tutorial.html#create-an-instance-of-the-mapped-class

**Comment by BrunoSanchez** [comment]
Now I think I understood: the backref is just for opposite-way queries, so they can be much faster, but the statement itself doesn't create a foreign key connection. Is it that?

**Comment by leliel12** [comment]
A wild bug appears 

```python
Traceback (most recent call last):
  File "run.py", line 11, in <module>
    cli.run_from_command_line(sys.argv[1:])
  File "/home/juan/proyectos/corral/src/corral/cli.py", line 206, in run_from_command_line
    core.setup_environment()
  File "/home/juan/proyectos/corral/src/corral/core.py", line 14, in setup_environment
    db.load_models_module()
  File "/home/juan/proyectos/corral/src/corral/db.py", line 35, in load_models_module
    return importlib.import_module(MODELS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/juan/proyectos/corral/src/toritos/models.py", line 68, in <module>
    class StateChange(db.Model):
  File "/home/juan/proyectos/corral/src/toritos/models.py", line 82, in StateChange
    pawprint_id = db.Column(db.Integer, db.ForeingKey('pawprint.id'))
AttributeError: 'module' object has no attribute 'ForeingKey'
```

Its *ForeignKey* no

**Comment by leliel12** [comment]
when i try to run `python run.py createdb --noinput`

```python
$ python run.py createdb --noinput
2015-10-21 11:59:53,676 INFO sqlalchemy.engine.base.Engine SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2015-10-21 11:59:53,676 INFO sqlalchemy.engine.base.Engine ()
2015-10-21 11:59:53,677 INFO sqlalchemy.engine.base.Engine SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2015-10-21 11:59:53,677 INFO sqlalchemy.engine.base.Engine ()
2015-10-21 11:59:53,678 INFO sqlalchemy.engine.base.Engine PRAGMA table_info("Pawprint")
2015-10-21 11:59:53,678 INFO sqlalchemy.engine.base.Engine ()
2015-10-21 11:59:53,678 INFO sqlalchemy.engine.base.Engine PRAGMA table_info("Observatory")
2015-10-21 11:59:53,678 INFO sqlalchemy.engine.base.Engine ()
2015-10-21 11:59:53,678 INFO sqlalchemy.engine.base.Engine PRAGMA table_info("StateChange")
2015-10-21 11:59:53,678 INFO sqlalchemy.engine.base.Engine ()
2015-10-21 11:59:53,678 INFO sqlalchemy.engine.base.Engine PRAGMA table_info("Campaign")
2015-10-21 11:59:53,678 INFO sqlalchemy.engine.base.Engine ()
2015-10-21 11:59:53,679 INFO sqlalchemy.engine.base.Engine PRAGMA table_info("Reference")
2015-10-21 11:59:53,679 INFO sqlalchemy.engine.base.Engine ()
2015-10-21 11:59:53,679 INFO sqlalchemy.engine.base.Engine PRAGMA table_info("StackStateChange")
2015-10-21 11:59:53,679 INFO sqlalchemy.engine.base.Engine ()
2015-10-21 11:59:53,679 INFO sqlalchemy.engine.base.Engine PRAGMA table_info("CalFile")
2015-10-21 11:59:53,679 INFO sqlalchemy.engine.base.Engine ()
2015-10-21 11:59:53,679 INFO sqlalchemy.engine.base.Engine PRAGMA table_info("Source")
2015-10-21 11:59:53,679 INFO sqlalchemy.engine.base.Engine ()
2015-10-21 11:59:53,679 INFO sqlalchemy.engine.base.Engine PRAGMA table_info("State")
2015-10-21 11:59:53,679 INFO sqlalchemy.engine.base.Engine ()
2015-10-21 11:59:53,679 INFO sqlalchemy.engine.base.Engine PRAGMA table_info("Combination")
2015-10-21 11:59:53,679 INFO sqlalchemy.engine.base.Engine ()
2015-10-21 11:59:53,680 INFO sqlalchemy.engine.base.Engine PRAGMA table_info("StackState")
2015-10-21 11:59:53,680 INFO sqlalchemy.engine.base.Engine ()
2015-10-21 11:59:53,680 INFO sqlalchemy.engine.base.Engine PRAGMA table_info("CCD")
2015-10-21 11:59:53,680 INFO sqlalchemy.engine.base.Engine ()
2015-10-21 11:59:53,680 INFO sqlalchemy.engine.base.Engine PRAGMA table_info("Candidate")
2015-10-21 11:59:53,680 INFO sqlalchemy.engine.base.Engine ()
2015-10-21 11:59:53,680 INFO sqlalchemy.engine.base.Engine PRAGMA table_info("MasterCal")
2015-10-21 11:59:53,680 INFO sqlalchemy.engine.base.Engine ()
Traceback (most recent call last):
  File "run.py", line 11, in <module>
    cli.run_from_command_line(sys.argv[1:])
  File "/home/juan/proyectos/corral/src/corral/cli.py", line 210, in run_from_command_line
    func(**args)
  File "/home/juan/proyectos/corral/src/corral/cli.py", line 80, in handle
    db.create_all()
  File "/home/juan/proyectos/corral/src/corral/db.py", line 39, in create_all
    return Model.metadata.create_all(*args, **kwargs)
  File "/home/juan/proyectos/corral/local/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 3687, in create_all
    tables=tables)
  File "/home/juan/proyectos/corral/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1856, in _run_visitor
    conn._run_visitor(visitorcallable, element, **kwargs)
  File "/home/juan/proyectos/corral/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1481, in _run_visitor
    **kwargs).traverse_single(element)
  File "/home/juan/proyectos/corral/local/lib/python2.7/site-packages/sqlalchemy/sql/visitors.py", line 121, in traverse_single
    return meth(obj, **kw)
  File "/home/juan/proyectos/corral/local/lib/python2.7/site-packages/sqlalchemy/sql/ddl.py", line 709, in visit_metadata
    [t for t in tables if self._can_create_table(t)])
  File "/home/juan/proyectos/corral/local/lib/python2.7/site-packages/sqlalchemy/sql/ddl.py", line 1058, in sort_tables_and_constraints
    dependent_on = fkc.referred_table
  File "/home/juan/proyectos/corral/local/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 2810, in referred_table
    return self.elements[0].column.table
  File "/home/juan/proyectos/corral/local/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 747, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/home/juan/proyectos/corral/local/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 1784, in column
    tablekey)
sqlalchemy.exc.NoReferencedTableError: Foreign key associated with column 'Pawprint.state_id' could not find table 'state' with which to generate a foreign key to target column 'id'
```

I think the problem is in statements like this one

```python
state_id = db.Column(db.Integer, db.ForeignKey('state.id'))
```

In the `db.ForeignKey` parameter i think the string represent `<TABLE_NAME>.<ATTRIBUTE>` and the table is `State` (the first letter must be capitalized). Please check the *State* model `__tablename__` class attribute
