### ISSUE TITLE
including core tables in models.py causes corral to fail

### ISSUE THREAD

**Issue by martinberoiz** [toros-astro/corral#18]
I think this is a bug, if instead of class models I include a not ORM table for the many to many it causes corral to fail.

Adding these tables

```
calib_combination = db.table(
    'calib_combination', db.Model.metadata,
    db.Column('calib_id', db.ForeignKey('calibfile.id'),
              primary_key=True),
    db.Column('combination_id', db.ForeignKey('combination.id'),
              primary_key=True))


paw_stack = db.table('paw_stack', db.Model.metadata,
                     db.Column('paw_id', db.ForeignKey('pawprint.id'),
                               primary_key=True),
                     db.Column('stack_id', db.ForeignKey('stack.id'),
                               primary_key=True))
```

results in this traceback:

```
$ corraldo createdb
/Users/utb/.virtualenvs/corral/lib/python2.7/site-packages/flask/exthook.py:71: ExtDeprecationWarning: Importing flask.ext.babel is deprecated, use flask_babel instead.
  .format(x=modname), ExtDeprecationWarning
Traceback (most recent call last):
  File "in_corral.py", line 10, in <module>
    cli.run_from_command_line()
  File "/Users/utb/Academia/Research/TOROS/Code/corral/corral/cli/__init__.py", line 157, in run_from_command_line
    parser = create_parser()
  File "/Users/utb/Academia/Research/TOROS/Code/corral/corral/cli/__init__.py", line 128, in create_parser
    load_commands_module()
  File "/Users/utb/Academia/Research/TOROS/Code/corral/corral/cli/__init__.py", line 119, in load_commands_module
    return util.dimport(COMMANDS_MODULE)
  File "/Users/utb/Academia/Research/TOROS/Code/corral/corral/util.py", line 40, in dimport
    return importlib.import_module(importpath)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/utb/Academia/Research/TOROS/Code/toritos_corral/toritos/commands.py", line 3, in <module>
    import models
  File "/Users/utb/Academia/Research/TOROS/Code/toritos_corral/toritos/models.py", line 290, in <module>
    primary_key=True))
  File "<string>", line 2, in table
  File "/Users/utb/.virtualenvs/corral/lib/python2.7/site-packages/sqlalchemy/sql/selectable.py", line 1334, in __init__
    self.append_column(c)
  File "/Users/utb/.virtualenvs/corral/lib/python2.7/site-packages/sqlalchemy/sql/selectable.py", line 1347, in append_column
    self._columns[c.key] = c
AttributeError: 'MetaData' object has no attribute 'key'
```

**Comment by leliel12** [comment]
This never gonna work, corral only supports the ORM to make models
